### PR TITLE
commit1

### PR DESCRIPTION
**Pull request by mynameissamir**

### CODE REVIEW

**Review by SaivijayK — CHANGES_REQUESTED** [review]
All good,
paragraph of text is missing in image.html(please check point:10 in document)

**Comment by saikiransathpadi** [comment]
layout is correct, for list items have a look on the spacing between lists

**Comment by mynameissamir** [comment]
sorry, but you're supposed to check assignment-4,but i have done the
changes youve said though in assignment-1 it is just not getting pushed
onto the same branch!

**Comment by mynameissamir** [comment]
done

**Pull request merged**
